export const GET = "GET"
export const POST = "POST"
export const PUT = "PUT"
export const DELETE = "DELETE"

export const COGAMI_API_URL = import.meta.env.VITE_COGAMI_BACKEND_URL
export const X_RAPIDAPI_KEY_IDEALISTA_POOL_0 = import.meta.env.VITE_X_RAPIDAPI_KEY_IDEALISTA_POOL_0
export const X_RAPIDAPI_KEY_IDEALISTA_POOL_1 = import.meta.env.VITE_X_RAPIDAPI_KEY_IDEALISTA_POOL_1
export const X_RAPIDAPI_KEY_IDEALISTA_POOL_2 = import.meta.env.VITE_X_RAPIDAPI_KEY_IDEALISTA_POOL_2
export const X_RAPIDAPI_KEY_IDEALISTA_POOL_3 = import.meta.env.VITE_X_RAPIDAPI_KEY_IDEALISTA_POOL_3
export const X_RAPIDAPI_KEY_IDEALISTA_POOL_4 = import.meta.env.VITE_X_RAPIDAPI_KEY_IDEALISTA_POOL_4
export const X_RAPIDAPI_KEY_IDEALISTA_POOL_5 = import.meta.env.VITE_X_RAPIDAPI_KEY_IDEALISTA_POOL_5
export const X_RAPIDAPI_KEY_IDEALISTA_POOL_6 = import.meta.env.VITE_X_RAPIDAPI_KEY_IDEALISTA_POOL_6
export const X_RAPIDAPI_KEY_IDEALISTA_POOL_7 = import.meta.env.VITE_X_RAPIDAPI_KEY_IDEALISTA_POOL_7
export const X_RAPIDAPI_HOST_IDEALISTA = import.meta.env.VITE_X_RAPIDAPI_HOST_IDEALISTA
export const X_RAPIDAPI_HOST_FOTOCASA = import.meta.env.VITE_X_RAPIDAPI_HOST_FOTOCASA
export const X_RAPIDAPI_IDEALISTA_GETALL = import.meta.env.VITE_X_RAPIDAPI_IDEALISTA_GETALL
export const X_RAPIDAPI_IDEALISTA_GETDETAIL = import.meta.env.VITE_X_RAPIDAPI_IDEALISTA_GETDETAIL
export const X_RAPIDAPI_FOTOCASA_GETALL = import.meta.env.VITE_X_RAPIDAPI_FOTOCASA_GETALL
export const X_RAPIDAPI_FOTOCASA_GETDETAIL = import.meta.env.VITE_X_RAPIDAPI_FOTOCASA_GETDETAIL

export const IDEALISTA_TOTAL_ELEMENTS_PER_PAGE = 40
export const FOTOCASA_TOTAL_ELEMENTS_PER_PAGE = 30